openapi: 3.0.0
info:
  title: Test project
  description: ONly for testing purpose
  version: 1.0.0
  contact:
    email: info@email.org
servers:
  - url: 'https://localhost:{port}'
    description: Local
    variables:
      port:
        enum:
          - '4444'
          - '5555'
          - '7777'
        default: '5555'
tags:
  - name: Example
    description: Example
paths:
  /activity:
    get:
      summary: getActivity
      description: get activity info
      operationId: getActivity
      tags:
        - Example
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/activity'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
components:
  schemas:
    ErrorObject:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              description: System-friendly error code for this Error.
            message:
              type: string
              description: |-
                Human-friendly error message for this Error.
                This error message is not intended for end-user presentation.
          required:
            - message
          additionalProperties: false
    activity:
      type: object
      additionalProperties: false
      properties:
        activity:
          type: string
        accessibility:
          type: string
        type:
          type: string
        participants:
          type: number
          nullable: false
        price:
          type: string
        link:
          type: string
          nullable: true
        key:
          type: string
          nullable: false
      required:
        - activity
        - accessibility
        - type
        - participants
        - price
        - link
        - key
  responses:
    '404':
      description: Requested URL not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorObject'
    '500':
      description: Internal Server error in case of issues on our side or if Bored API throws an error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorObject'
